lots of fixes and new features

diff --git a/vmh-connect b/vmh-connect
--- a/vmh-connect
+++ b/vmh-connect
@@ -1,75 +1,84 @@
 #!/bin/sh
 
+# help
+if [ -z "$1" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+    echo "virt-viewer wrapper"
+    echo ""
+    echo "Example use:"
+    echo "  windowed:   vmh-connect my.domain"
+    echo "  kiosk:      vmh-connect my.domain -k"
+    echo "  fullscreen: vmh-connect my.domain -f"
+    exit 0
+fi
+
 # must run as normal user
 if [ "$(id -u)" = 0 ]; then
-	echo 'This script must be run as a normal user, not root!' >&2
-	exit 1
+    echo 'This script must be run as a normal user, not root!' >&2
+    exit 1
 fi
 
 # set default URI
-export LIBVIRT_DEFAULT_URI="qemu:///system"
+if [ -z "$LIBVIRT_DEFAULT_URI" ]; then
+    export LIBVIRT_DEFAULT_URI="qemu:///system"
+fi
+
+# set default display
+if [ -z "$DISPLAY" ]; then
+    export DISPLAY=:0
+fi
 
 DOMAIN="$1"
 ARG="$2"
 FULL_ARG=""
 if [ "$ARG" = "-f" ]; then
-	FULL_ARG="-f"
+    FULL_ARG="-f"
 elif [ "$ARG" = "-k" ]; then
-	FULL_ARG="-k"
+    FULL_ARG="-k"
 fi
 
 error() {
-	# logger -t "vmhandler" "ERROR: $DOMAIN: $1"
-	echo "ERROR: $DOMAIN: $1" >&2
-	exit 1
+    # logger -t "vmhandler" "ERROR: $DOMAIN: $1"
+    echo "ERROR: $DOMAIN: $1" >&2
+    exit 1
 }
 
 warn() {
-	# logger -t "vmhandler" "WARNING: $DOMAIN: $1"
-	echo "WARNING: $DOMAIN: $1" >&2
+    # logger -t "vmhandler" "WARNING: $DOMAIN: $1"
+    echo "WARNING: $DOMAIN: $1" >&2
 }
 
 info() {
-	# logger -t "vmhandler" "INFO: $DOMAIN: $1"
-	echo "INFO: $DOMAIN: $1" >&2
+    # logger -t "vmhandler" "INFO: $DOMAIN: $1"
+    echo "INFO: $DOMAIN: $1" >&2
 }
 
 webinfo() {
-	echo "$1"
+    echo "$1"
 }
 
-is_imported() {
-	if [ -z "$1" ]; then
-		error "is_imported: variable is unset or empty"
-	fi
-
-	if virsh -q list --all --name | grep -qx "$1"; then
-		return 0
-	else
-		return 1
-	fi
-}
-
-is_running() {
-	if [ -z "$1" ]; then
-		error "is_running: variable is unset or empty"
-	fi
-
-	if virsh -q list --name --state-running | grep -qx "$1"; then
-		return 0
-	else
-		return 1
-	fi
-}
-if ! is_imported "$DOMAIN"; then
-	error "Domain is not imported"
-fi
-if ! is_running "$DOMAIN"; then
-	error "Domain is not running"
+# verify input
+if [ -z "$DOMAIN" ]; then
+    error "Must specify a DOMAIN"
 fi
 
-info "exporting new display: $DISPLAY"
-export DISPLAY=:0 1>&2 # todo: find all displays first
+#is_running() {
+#	if [ -z "$1" ]; then
+#		error "is_running: variable is unset or empty"
+#	fi
+#
+#	# shellcheck disable=SC2009
+#	if ps -ef | grep qemu-system-x86_64 | grep -qx "guest=$1"; then
+#		return 0
+#	else
+#		return 1
+#	fi
+#}
+#if [ -z "$FULL_ARG" ]; then
+#    if ! is_running "$DOMAIN"; then
+#        error "Domain is not running"
+#    fi
+#fi
+
 info "trying to connect to: $DOMAIN"
 # shellcheck disable=SC2086
 virt-viewer "$DOMAIN" --reconnect --wait $FULL_ARG 1>/dev/null 2>/dev/null &
diff --git a/vmh-logging-enable b/vmh-logging-enable
--- a/vmh-logging-enable
+++ b/vmh-logging-enable
@@ -3,22 +3,25 @@
 
 # must run as root
 if [ "$(id -u)" -ne 0 ]; then
-    echo 'This script must be run as root!' >&2
-    exit 1
+	echo 'This script must be run as root!' >&2
+	exit 1
 fi
 
 # already enabled
 if [ -f "/etc/rsyslog.d/99-vmhandler.conf" ]; then
-    exit 0
+	exit 0
 fi
 
-echo ":syslogtag, startswith, \"vmhandler\" /var/log/vmhandler.log
+# shellcheck disable=SC2016
+echo "\$FileCreateMode 0644
+\$umask 0644
+:syslogtag, startswith, \"vmhandler\" /var/log/vmhandler.log
 & stop
 " >"/etc/rsyslog.d/99-vmhandler.conf"
 
 if [ -z "$(command -v systemctl)" ]; then
-    echo "systemctl not found. Please restart the rsyslog service manually."
-    exit 1
+	echo "systemctl not found. Please restart the rsyslog service manually."
+	exit 1
 fi
 
 systemctl restart rsyslog.service
